// swift-tools-version: 5.6

// WARNING:
// This file automatically generated by Swift Playgrounds.
// Do not remove.
import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MiniNote",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MiniNote",
            targets: ["AppModule"],
            bundleIdentifier: "com.yourname.mininote",
            teamIdentifier: nil,
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .pencil),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)